<a href="https://colab.research.google.com/github/DrPravallika/Python-Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Importing Numpy library  from python and checking its version
import numpy as np
print(np.__version__)

1.25.2


In [ ]:
#Creating 1D array with its type , data type, dimension
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
print(arr.dtype)
arr.ndim

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int64


1

In [ ]:
#Creating 2D array with its type , data type, dimension,shape
arr2d=np.array([[1,2],[3,4],[5,6]])
print(arr2d)
print(type(arr2d))
arr2d.ndim
print(arr2d.dtype)
print(arr2d.shape)


[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
int64
(3, 2)


In [ ]:
arr2dnew=arr2d.reshape(2,3,1)

In [ ]:
print(arr2dnew)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [ ]:
#Creating 3D array with its type , data type, dimension,shape
arr3d=np.array([    [[1,2],[3,4]] , [[4,5],[6,7]] ,  [[8,9],[10,11]]        ])
print(arr3d)
print(type(arr3d))
print(arr3d.ndim)
print(arr3d.shape)
print(arr3d.dtype)
#Indexing
print(arr3d[0,1,0])


In [ ]:
#Indexing type 2
#start,stop,step
print(arr3d[1:5:1])

In [ ]:
#Indexing type 3
#start list no: end list no , element : element
print(arr3d[0:1,1])

[[3 4]]


In [ ]:
#Reshape 3d array to 2d array
print(arr3d.reshape(2,6))

[[ 1  2  3  4  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
#Using For Loop
for x in arr3d:
 for y in x:
  for z in y:
   print(z)


1
2
3
4
4
5
6
7
8
9
10
11


In [6]:
#Concatenation
arr1=np.array([[[1,2],[3,4]]])
arr2=np.array([[[5,6],[7,8]]])
r=np.concatenate((arr1,arr2),axis=0)
print(r)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
#Concatenation
arr1=np.array([[[1,2],[3,4]]])
arr2=np.array([[[5,6],[7,8]]])
r=np.concatenate((arr1,arr2),axis=1)
print(r)


[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [13]:
#Transpose- Convert row to column and vice-versa
arrbt=np.array([[[1,2],[3,4],[5,6]]])
arrat=arrbt.transpose()
print('array before transpose:' , arrbt)
print('array after transpose:', arrat)

array before transpose: [[[1 2]
  [3 4]
  [5 6]]]
array after transpose: [[[1]
  [3]
  [5]]

 [[2]
  [4]
  [6]]]


In [7]:
#axis=1 , vertical , axis=0 ,horizontal , axis=1
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arrnew=np.vstack([arr1,arr2])
print(arrnew)
arrnew1=np.hstack([arr1,arr2])
print(arrnew1)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [ ]:
arrsplit=np.a

In [11]:
#Arange Function(start,stop,step)
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
#Split Function
arrsplit=np.split(arr,2)
print(arrsplit)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [18]:
#Where Function
np.where(arr > 2)

(array([3, 4, 5, 6, 7, 8, 9]),)

In [21]:
#Conversion of data type using astype method
arr=np.array([1,2,3,4,5])
print(arr.dtype)
arr1=arr.astype(bool)
print(arr1.dtype)

int64
bool


In [25]:
r=np.random.randint(1,2)
print(r)

1


In [27]:
#addition
p=np.array([1,2,3])
q=np.array([4,5,6])
r=np.add(p,q)
print(r)

[5 7 9]


In [30]:
#substraction
p=np.array([1,2,3])
q=np.array([4,5,6])
r=np.subtract(p,q)
print(r)

[-3 -3 -3]


In [31]:
#multiplication
p=np.array([1,2,3])
q=np.array([4,5,6])
r=np.dot(p,q)
print(r)

32


RANDOM
RANDINT(LOW,HIGH=NONE,SIZE,DTYPE)


In [54]:
import random
x=random.randint(2,10)
print(x)
x=np.random.choice([1,2,3,4,5,6],p=(0.1,0.2,0.4,0.1,0.1,0.1),size=(1,1))
print(x)

6
[[4]]


The random.normal() function in Python generates random numbers from a normal distribution with a specified mean and standard deviation. The syntax of the function is as follows:


random.normal(loc=0.0, scale=1.0, size=None)

loc: The mean of the normal distribution. Default is 0.0.
scale: The standard deviation of the normal distribution. Default is 1.0.
size: The shape of the output array. Default is None, which generates a single random number.
Here's an example of how to use the random.normal() function:


import random

# Generate 10 random numbers from a normal distribution with mean 5 and standard deviation 2
### random_numbers = random.normal(loc=5, scale=2, size=10)

In [57]:
random_numbers = np.random.normal(loc=5, scale=2, size=10)
print(random_numbers)

[8.49764112 4.84645315 6.33751625 5.95479057 5.32496238 5.36780095
 3.89173217 5.92926319 6.4689038  7.69666088]


In [59]:
x='end of numpy'
print(x)


end of numpy
